name: m5_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - pandas
  - numpy
  - scikit-learn
  - lightgbm
  - plotly
  - dvc
  - dvc-s3
  - optuna
  - mlflow
  - ipywidgets
  - pip
  - pip:
      - kaggle
      - prophet        
